name: CodeCov

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 5 * * *'

jobs:
  industrial_ci:
    name: CodeCov
    runs-on: ubuntu-latest
    env:
      CI_NAME: CodeCov
      OS_NAME: ubuntu
      OS_CODE_NAME: bionic
      ROS_DISTRO: melodic
      ROS_REPO: main
      UPSTREAM_WORKSPACE: 'dependencies_with_ext.rosinstall'
      ROSDEP_SKIP_KEYS: "bullet cmake_common_scripts iwyu fcl taskflow"
      DOCKER_IMAGE: "rosindustrial/tesseract:melodic"
      CCACHE_DIR: "/home/runner/work/tesseract_planning/tesseract_planning/CodeCov/.ccache"
      UPSTREAM_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Release"
      TARGET_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug -DTESSERACT_ENABLE_CODE_COVERAGE=ON"
      AFTER_SCRIPT: 'catkin build -w $target_ws --no-deps --verbose tesseract_command_language tesseract_motion_planners tesseract_process_managers tesseract_time_parameterization --make-args ccov-all
                     && bash <(curl -s https://codecov.io/bash) -t a89e6f59-5409-4686-b615-b2341c7ef69a -s $target_ws/build -f *all-merged.info'
    steps:
      - uses: actions/checkout@v1

      - name: Free Disk Space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: ccache cache files
        uses: actions/cache@v1.1.0
        with:
          path: ${{ env.CI_NAME }}/.ccache
          key: ${{ env.CI_NAME }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ env.CI_NAME }}-ccache-

      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{env}}
